### ISSUE TITLE
AttributeError: 'Timedelta' object has no attribute 'astype' #49

### ISSUE THREAD

**Issue by muschellij2** [OxWearables/actipy#28]
Same issue as https://github.com/OxWearables/stepcount/issues/49, which is causing stepcount to fail.

# Issue
It seems as though the detect non-wear has issues when `timedelta` has too few 

# Data to reproduce
[P30_wrist100.csv.gz](https://github.com/OxWearables/actipy/files/13834405/P30_wrist100.csv.gz)

This is from https://ora.ox.ac.uk/objects/uuid:19d3cb34-e2b3-4177-91b6-1bad0e0163e7.

## Code to reproduce

```python
import actipy
import pandas as pd

filepath = "P30_wrist100.csv.gz"
data = pd.read_csv(
  filepath,
  usecols=['time', 'x', 'y', 'z'],
  parse_dates=['time'],
  index_col='time',
  dtype={'x': 'f4', 'y': 'f4', 'z': 'f4'},
)

data, info = actipy.process(
  data, 
  sample_rate=15,
  lowpass_hz=None,
  calibrate_gravity=True,
  detect_nonwear=True,
  resample_hz="uniform",
  verbose=True
)
```

With output and error
```
>>> import actipy
>>> import pandas as pd
>>> 
>>> filepath = "P30_wrist100.csv.gz"
>>> data = pd.read_csv(
...   filepath,
...   usecols=["time", "x", "y", "z"],
...   parse_dates=["time"],
...   index_col="time",
...   dtype={"x": "f4", "y": "f4", "z": "f4"},
... )
>>> 
>>> data, info = actipy.process(
...   data, 
...   sample_rate=15,
...   lowpass_hz=None,
...   calibrate_gravity=True,
...   detect_nonwear=True,
...   resample_hz="uniform",
...   verbose=True
... )
/Users/johnmuschelli/miniconda3/envs/stepcount/lib/python3.9/site-packages/actipy/processing.py:294: UserWarning: Skipping calibration: Insufficient stationary samples: 1 < 50
  warnings.warn(f"Skipping calibration: Insufficient stationary samples: {len(xyz)} < {calib_min_samples}")
Gravity calibration... Done! (0.04s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johnmuschelli/miniconda3/envs/stepcount/lib/python3.9/site-packages/actipy/reader.py", line 144, in process
    data, info_nonwear = P.detect_nonwear(data)
  File "/Users/johnmuschelli/miniconda3/envs/stepcount/lib/python3.9/site-packages/actipy/processing.py", line 201, in detect_nonwear
    stationary_segment_ids
AttributeError: 'Timedelta' object has no attribute 'astype'
```

Without detecting non-wear:
```python
>>> data, info = actipy.process(
...   data, 
...   sample_rate=15,
...   lowpass_hz=None,
...   calibrate_gravity=True,
...   detect_nonwear=False,
...   resample_hz="uniform",
...   verbose=True
... )
actipy/processing.py:294: UserWarning: Skipping calibration: Insufficient stationary samples: 1 < 50
  warnings.warn(f"Skipping calibration: Insufficient stationary samples: {len(xyz)} < {calib_min_samples}")
Gravity calibration... Done! (0.04s)
Resampling... Done! (0.04s)
```

**Comment by muschellij2** [comment]
Upgrading to 3.0.5 resolved this issue.
