### ISSUE TITLE
No JVM shared library file

### ISSUE THREAD

**Issue by abramschon** [OxWearables/actipy#9]
After installing java, (java -version returns openjdk version "19.0.1" 2022-10-18) and python (python --version returns Python 3.10.6), trying to run actipy returns:
Traceback (most recent call last):
  File "/Users/aschonfeldt/Desktop/brams data/match_annotations.py", line 4, in <module>
    data, info = actipy.read_device("raw_data/CWA-DATA.CWA",
  File "/Users/aschonfeldt/Desktop/brams data/.venv/lib/python3.10/site-packages/actipy/reader.py", line 49, in read_device
    data, info_read = _read_device(input_file, verbose)
  File "/Users/aschonfeldt/Desktop/brams data/.venv/lib/python3.10/site-packages/actipy/reader.py", line 167, in _read_device
    info_java = java_read_device(input_file, tmpout, verbose)
  File "/Users/aschonfeldt/Desktop/brams data/.venv/lib/python3.10/site-packages/actipy/reader.py", line 203, in java_read_device
    setupJVM()
  File "/Users/aschonfeldt/Desktop/brams data/.venv/lib/python3.10/site-packages/actipy/reader.py", line 230, in setupJVM
    jpype.startJVM(convertStrings=False)
  File "/Users/aschonfeldt/Desktop/brams data/.venv/lib/python3.10/site-packages/jpype/_core.py", line 184, in startJVM
    jvmpath = getDefaultJVMPath()
  File "/Users/aschonfeldt/Desktop/brams data/.venv/lib/python3.10/site-packages/jpype/_jvmfinder.py", line 74, in getDefaultJVMPath
    return finder.get_jvm_path()
  File "/Users/aschonfeldt/Desktop/brams data/.venv/lib/python3.10/site-packages/jpype/_jvmfinder.py", line 212, in get_jvm_path
    raise JVMNotFoundException("No JVM shared library file ({0}) "
jpype._jvmfinder.JVMNotFoundException: No JVM shared library file (libjli.dylib) found. Try setting up the JAVA_HOME environment variable properly.

**Comment by chanshing** [comment]
Hi @abramschon 
The package still doesn't support Windows, unfortunately!

**Comment by chanshing** [comment]
Should be fixed now. Re-open if not: https://github.com/OxWearables/actipy/releases/tag/v2.0.0
